# Generated by Django 4.2 on 2024-08-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitente', models.CharField(max_length=100)),
                ('destinatario', models.TextField(max_length=100)),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
